### PR TITLE
Fix dependency wrongly declared as devDependency

### PR DESCRIPTION
**Pull request by klzns**
I tried to use this package, but I got this error:

image

This happened because a dependency was declared as a devDependency. This PR fixes this.

### CODE REVIEW

**Comment by klzns** [comment]
Added another commit to fix the file the `main` property on `package.json` as pointing to. Before that it was pointing to a not transpiled version in `src`.

**Comment by guilhermearaujo** [comment]
Much appreciated! Right now I am working on a larger overhaul, changing the build system to web pack and these fixes are included too.

I just need to fix a small issue with code coverage reports, but I expect it to be published really soon.

**Comment by klzns** [comment]
That's great news! Let me know if you need a hand!

**Comment by guilhermearaujo** [comment]
@klzns fixed on #17 and a few other commits after that.
Version 1.1.0 is now live on npm.

**Pull request closed without merging**
